#include "eyes_common.h"

#if (NUM_EYES == 2)
eyeInfo_t eyeInfo[] = {
#if CONFIG_IDF_TARGET_ESP32C3
    {TFT1_CS, LH_WINK_PIN, TFT_1_ROT, EYE_1_XPOSITION, EYE_1_YPOSITION, TFT1_DC, TFT1_RST, TFT1_BL},
    {TFT2_CS, RH_WINK_PIN, TFT_2_ROT, EYE_2_XPOSITION, EYE_2_YPOSITION, TFT2_DC, TFT2_RST, TFT2_BL},
#else
    {TFT1_CS, LH_WINK_PIN, TFT_1_ROT, EYE_1_XPOSITION, EYE_1_YPOSITION, LCD_PIN_DC, LCD_PIN_RST, LCD_PIN_BL},
    {TFT2_CS, RH_WINK_PIN, TFT_2_ROT, EYE_2_XPOSITION, EYE_2_YPOSITION, LCD_PIN_DC, LCD_PIN_RST, LCD_PIN_BL},
#endif
};
#else
eyeInfo_t eyeInfo[] = {
    {TFT1_CS, LH_WINK_PIN, TFT_1_ROT, EYE_1_XPOSITION, EYE_1_YPOSITION, LCD_PIN_DC, LCD_PIN_RST, LCD_PIN_BL},
};
#endif